/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.elyograg.test.haproxy;

import org.junit.Test;

public final class MainSSLTestTests {
  @Test
  final void someTest() {

  }
}
